name: Trigger secondary workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  actions: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger secondary workflow
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.MY_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/secondary-workflow.yml/dispatches \
          -d '{"ref":"${{ github.ref }}"}'
